apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: gasoline-tracker
spec:
  type: NodePort
  ports:
    - port: 9000
      protocol: TCP
      nodePort: 31112
  selector:
    app: backend
