apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend
  namespace: gasoline-tracker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: jvisser/gt-app:latest
        env:
          - name: DATABASE_HOST
            value: database
          - name: DATABASE_PORT
            value: '3306'
          - name: DATABASE_NAME
            value: gasoline-tracker
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: password
        ports:
        - containerPort: 9000
