apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: gasoline-tracker
spec:
  type: NodePort
  ports:
    - port: 3306
      protocol: TCP
      nodePort: 31111
  selector:
    app: database
