apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: gasoline-tracker
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      nodePort: 31113
  selector:
    app: frontend
