apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: proxy
  namespace: gasoline-tracker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: jvisser/gt-proxy:latest
        ports:
        - containerPort: 80
